config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user, only: %i[edit update]
  resources :suggestions, only: %i[edit destroy update] do
    resources :votes, only: %i[create]
  end
  resources :invites, only: %i[edit update destroy]
  resources :events do
    resources :suggestions, only: %i[create]
    resources :invites, only: %i[create]
    resources :messages, only: %i[new create index]
  end

  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="flex-grow-1">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <div>
    <i class="fas fa-list-alt nav-link active" data-toggle="modal" data-target="#eventsListModal" id="nav-icon"></i>
  </div>
  <div>
    <i class="fas fa-envelope nav-link active" data-toggle="modal" data-target="#pendingEventsModal" id="nav-icon"><div id="invites-count"><%= Invite.where(email: current_user.email).where(accepted: nil).count %></div></i>
  </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li>
        <%= link_to current_user.email , "#" , class: "nav-link" %>
      </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.url.nil? %>
            <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
             <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
             <!-- link_to "Another action", "#", class: "dropdown-item" -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<!--Modal de eventos-->

<div class="modal fade" id="eventsListModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="eventsListModalContent">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your events</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body overflow-auto" style="height:50vh;">
          <% @current_user_events.each do |event| %>
          <div class="card">
            <div class="card-header">
              <span style="font-size:20px;"><%= event.title %></span> <strong>(<%= (event.user == current_user ? 'Owner' : 'Invited') %>)</strong>
            </div>
            <div class="card-body">
              <strong style="color:#5C005C"><%= event.date.strftime('%a, %b %e (%I:%M %p)') %></strong>
              <div class="d-flex flex-row mt-2">
              <div class="ml-2" style="flex-grow:1;">
                <%= link_to event_path(event), id: "event-details-link" do %>
                <i class="fas fa-info-circle" style="font-size: 20px; color:#5C005C; margin-right:8px;"></i>
                <% end %>
              </div>
              <div>
                <%= link_to event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete it?" } do %>
                <i class="far fa-trash-alt" style="color:#FF708A; font-size: 20px; margin-right:8px;"></i>
                <% end %>
              </div>
              </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- modal de eventos pendentes -->

<div class="modal fade" id="pendingEventsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="dayEventsModalContent">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your pending invites</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if current_user %>
          <% unless @pending_invites.empty? %>
            <% @pending_invites.each do |invite| %>
              <div class="d-flex flex-row justify-content-between" id="event-item" style="border-bottom: 1px solid lightgrey; margin-bottom: 20px;">
                <div>
                  <strong style="color:#5C005C"><%= invite.event.date.strftime('%A %e, %B %Y at %I:%M %p') %></strong> | <%= invite.event.title %>
                </div>
                <div class="ml-2" style="flex-grow:1;">
                  <%= link_to invite_path(invite), method: :delete do %>
                    <i class="far fa-thumbs-down" style="color:#5c005c; margin-right:8px;"></i>
                  <% end %>
                </div>
                <div class="ml-2" style="flex-grow:1;">
                  <%= link_to invite_path(invite), method: :patch do %>
                    <i class="far fa-thumbs-up" style="color:#FF708A; margin-right:8px;"></i>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
          <% else %>
            <h5 style="color: #5C005C;">You have no invites pending.</h5>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>