config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user, only: %i[edit update]
  resources :suggestions, only: %i[edit destroy update] do
    resources :votes, only: %i[create]
  end
  resources :invites, only: %i[edit update destroy]
  resources :events do
    resources :suggestions, only: %i[create]
    resources :invites, only: %i[create]
    resources :messages, only: %i[new create index]
  end

  mount ActionCable.server => "/cable"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :suggestions, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :title, presence: true, length: { maximum: 40, too_long: "Title must have at most %{count} characters." }
  validates :date, presence: true
  validates :description, presence: true, length: { maximum: 150, too_long: "Description must have at most %{count} characters." }

  mount_uploader :photo, PhotoUploader
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show destroy]
  before_action :event_params, only: %i[create]

  def index
    @events = policy_scope(Event)
    @pending_invites = Invite.where(email: current_user.email).where(accepted: nil)
    @event = Event.new
    unless @pending_invites.empty?
      flash[:alert] = "You have #{@pending_invites.count} invite#{"s" if @pending_invites.count > 1} pending. Click on the envelope icon"
    end
  end

  def create
    @event = Event.new(event_params)
    time = params[:event_time].values.last(2)
    date = params[:event_date].values.first
    @event.user = current_user

    if params[:event_date].values.first.empty?
      @event.date = ""
    else
      @event.date = Time.parse("#{date}T#{time[0]}:#{time[1]}")
    end

    authorize @event
    if @event.save
      redirect_to event_path(@event)
    else
      flash[:alert] = @event.errors.values.flatten.first
      @events = policy_scope(Event)
      @pending_invites = Invite.where(email: current_user.email).where(accepted: nil)

      render :index
    end
  end

  def show
    @invite = Invite.new()
    @suggestion = Suggestion.new()
    @message = Message.new()
    @suggestion_selected = @event.suggestions.find_by(selected: true)
    @confirmed = @event.invites.where(accepted: true)
    @invited = @event.invites.all
    @messages = Message.where(event_id: @event).order(:created_at)

    @suggest_map = @event.suggestions.where.not(latitude: nil, longitude: nil).where(selected: true)
    @markers = @suggest_map.map do |flatten|
      {
        lat: flatten.latitude,
        lng: flatten.longitude
      }
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def find_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:title, :description, :photo)
  end
end

app/views/events/_chat.html.erb
<div class="chat-general">
    <div class="col-12 d-flex flex-column justify-content-between chat-groups">
      <div class="d-flex flex-column flex-grow-1 ml-2 mt-2 chat-messages">
        <div id="chat-content" class="d-flex flex-column flex-grow-1">
          <% @messages.each do |message|%>
            <%= render 'message', message: message, user_is_messages_author: message.user == current_user %>
          <% end %>
        </div>
      </div>
      <div class="chat-input-form">
      <%= simple_form_for [@event, @message], wrapper: :inline_form, html: { class: "form-inline" }, remote: true do |f|%>
        <div class="flex-grow-1">
        <%= f.input :content, label: false, as: :string, input_html: { class: "ml-1 mb-1 mt-1 mr-sm-1 w-100", id:"input-chat" }%>
        </div>
        <%= f.button :button do %>
          <i class="fas fa-paper-plane" style="color:#5c005c; font-size:30px;"></i>
        <% end %>
      <% end %>
    </div>
</div>

<% content_for :after_js do %>
  <script>
    App['chat_<%= @event.id %>'] = App.cable.subscriptions.create(
      { channel: "ChatChannel", event_id: <%= @event.id %> },
      {
        connected: function() {
          console.log("Connected to the chat channel");
        },
        disconnected: function() {
          console.log("Disconnected from the chat channel");
        },
        received: function(data) {
          if (data.current_user_id !== <%= current_user.id %>) {
            const messages = document.querySelector('#chat-content');
            messages.insertAdjacentHTML('beforeend', data.message_partial);
            messages.scrollTop = messages.scrollHeight;
          }
        }
      });
  </script>
<% end %>

app/views/events/_message.html.erb
<div>
  <% if user_is_messages_author %>
    <div class="d-flex flex-column mr-2 mt-2 align-items-end" style="text-align-right;">
        <div style="padding: 10px 10px 1px 10px;"></div>
        <div style="padding:10px; max-width: 70%; margin-bottom: -15px;">
          <div id="message-user-content"><%= message.content %></div>
        </div>
    </div>
  <% else %>
    <div class="d-flex flex-column align-items-start">
      <div style="padding: 10px 10px 1px 10px;">
        <strong style="color:#5c005c; font-size:12px;"><%= message.user.email %></strong>
      </div>
      <div style="padding:10px; max-width: 70%; margin-bottom: -15px;">
        <div id="message-invite-content"><%= message.content %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_modal.html.erb
<div class="modal fade" id="dayEventsModal<%= date %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="dayEventsModalContent">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your events on <%= date.strftime('%A %e, %B %Y') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <% events.each do |event| %>
          <div class="d-flex flex-row justify-content-between" id="event-item" style="border-bottom: 1px solid lightgrey; margin-bottom: 20px;">
              <div>
              <strong style="color:#5C005C"><%= event.date.strftime('%I:%M %p') %></strong> | <%= event.title %> (<%= (event.user == current_user ? 'Owner' : 'Invited') %>)
              </div>
              <div class="ml-2" style="flex-grow:1;">
                <%= link_to event_path(event), id: "event-details-link" do %>
                <i class="fas fa-info-circle" style="font-size: 15px; color:#5C005C; margin-right:8px;"></i>
                <% end %>
              </div>
              <div>
                <% if event.user == current_user %>
                  <%= link_to event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete it?" } do %>
                  <i class="far fa-trash-alt" style="color:#FF708A; margin-right:8px;"></i>
                  <% end %>
                <% else %>
                  <% invite = current_user.invites.find_by(event: event)%>
                  <%= link_to invite_path(invite.id), method: :delete, data: {confirm: "Are you sure you want to delete your invitation?"} do %>
                    <i class="far fa-trash-alt" style="color:#FF708A; margin-right:8px;"></i>
                  <% end %>
                <% end %>
              </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="pendingEventsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="dayEventsModalContent">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your pending events</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @pending_invites.each do |invite| %>
          <div class="d-flex flex-row justify-content-between" id="event-item" style="border-bottom: 1px solid lightgrey; margin-bottom: 20px;">
            <div>
              <strong style="color:#5C005C"><%= invite.event.date.strftime('%A %e, %B %Y at %I:%M %p') %></strong> | <%= invite.event.title %>
            </div>
            <div class="ml-2" style="flex-grow:1;">
              <%= link_to invite_path(invite), method: :patch do %>
              <i class="far fa-thumbs-up" style="color:#FF708A; margin-right:8px;"></i>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-fluid" style="height: 90vh;">
  <div class="row">
    <div class="col-xl-5 col-lg-12 col-md-12 col-sm-12" style="height: 90vh;">
      <div class="d-flex flex-column justify-content-center align-items-center m-3 p-1" id="new-event-container">
        <div>
        <h1 style="margin-bottom: 10px; font-size: 30px; color: #666666;">Create an event</h1>
        </div>
          <!-- FORM BEGIN -->
          <div class="form-event" style="width: 20rem;">
            <%= simple_form_for @event  do |f| %>
              <%= f.input :title, label: false, placeholder: "Title"  %>
              <%= f.input :description, label: false, placeholder: "Description"  %>
              <div class="row" style="width: 20rem; margin-left: 0px;">
                <div class="col-6 p-0">
                  <%= f.input :date, as: :string, placeholder: "Click on a day", disabled: true, label: false %>
                </div>
                <div class="col-6 p-0">
                  <%= simple_fields_for :event_time do |field| %>
                    <%= field.input :event_time, as: :time, minute_step: 15, label: false, id: "time-input" %>
                  <% end %>
                  <%= simple_fields_for :event_date do |field| %>
                    <%= field.input :event_date, as: :hidden, label: false %>
                  <% end %>
                </div>
              </div>
              <div class="d-flex flex-row justify-content-between w-100" style="margin: 0px;">
                <div class="w-50 ml-0" id="inputbox" style="max-width: 150px; font-size:30px; background-image: url('<%= image_path 'camera-solid.svg'%>');">
                  <%= f.input :photo, label: false, input_html: { style: "padding: 0px;" }%>
                  <%= f.input :photo_cache, as: :hidden %>
                </div>
                <div class="w-50 d-flex justify-content-end" style="margin: 0px; padding: 0px;">
                  <%= f.submit 'Create Event', class:"btn btn-primary btn-create", input_html: {style:"z-index: 0;"}%>
                </div>
              </div>
            <% end %>
          </div>
        <!-- FORM END -->
      </div>
      <div class="d-flex flex-column justify-content-center align-items-center m-3">
        <!-- CALENDAR BEGIN -->
        <div>
        <div>
          <%= month_calendar(attribute: :date, events: @events) do |date, events| %>
            <div id="calendar-day">
              <% if events.present? %>
                <a id="events-modal-link" data-toggle="modal" data-target="#dayEventsModal<%= date %>">
              <% end %>
                <span id="day-text" style="cursor: pointer;"><%= date.day %></span>
              <% if events.present? %>
                </a>
              <% end %>
                <%= hidden_field_tag('calendar-datetime', date) %>
              <% events.each do |event| %>
              <% end %>
            </div>
            <%= render 'modal', events: events, date: date %>
          <% end %>
        </div> <!-- CALENDAR END -->
        <div class="d-flex flex-column justify-content-center">
          <div style="text-align:center;">
            <span style="color: rgba(102,102,102, 0.6);">* Click on a day to see your events</span>
          </div>
          <div class="mt-1 below-calendar d-flex flex-row justify-content-between" style="text-align:center;">
            <a class="below-calendar-links" data-toggle="modal" data-target="#eventsListModal" style="cursor: pointer;">Your events</a>
            <a class="below-calendar-links" id="pending-modal" data-toggle="modal" data-target="#pendingEventsModal" style="cursor: pointer;">Pending invites (<%= @pending_invites.count %>)</a>
          </div>
        </div>
        </div>
      </div>
    </div> <!-- LEFT CONTAINER END -->

    <div class="d-none d-xl-block col-xl-7 col-lg-12 col-md-12 col-sm-12 col-xs-12" style="background-image: url('<%= image_path 'index_foto.jpg' %>'); background-size:cover;">
    </div>
</div>
<%= javascript_pack_tag 'datepicker.js' %>

app/views/events/index.js.erb
const modalBox = document.getElementById("caixa_pro_modal");

modalBox.insertAdjacentHTML("beforeend", "<%= render 'modal' %>")

$("#dayEventsModal").modal();

app/views/events/show.html.erb
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />

<div class="container-fluid">
  <div class="row" style="height:85vh;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-7">
      <div class="d-flex flex-column">

        <!--Title do aniversario-->
        <div class="row d-xl-none d-md-none justify-content-center" style="border-bottom:5px solid #5c005c; background:#ce6a85; text-align:center;">
            <h1 style="color:white;"><%= @event.title %></h1>
        </div>
        <% if @event.photo.file.nil? %>
        <div class="row d-none d-md-block" style="height: 55vh; background-image: url('<%= image_path 'show.jpg' %>'); background-size:cover; border-bottom:5px solid #5c005c; position:relative;">
          <div class="d-flex flex-row justify-content-start title-show-banner-content">
            <h1><%= @event.title %></h1>
          </div>
        </div>
        <% else %>
        <div class="row d-none d-md-block" style="height: 55vh; background-image: url('<%= cl_image_path @event.photo %>'); background-size:cover; border-bottom:5px solid #5c005c; position:relative;">
          <div class="d-flex flex-row justify-content-start title-show-banner-content">
            <h1><%= @event.title %></h1>
          </div>
        </div>
        <% end %>
        <!--End-->

        <!--Inicio dos detalhes-->
        <div class="row justify-content-around details-show-content p-0">
          <div class="col-lg-9 col-md-12">
            <div class="d-flex flex-column justify-content-between">
            <div class="d-flex flex-column">
            <div class="mt-3" style="position:relative;">
              <% @confirmed.first(3).each do |accept| %>
                <span data-toggle="tooltip" data-placement="top" title="<%= accept.user.email %>"><%= cl_image_tag accept.user.photo, class: "avatar_details" %></span>
              <% end %>
              <a href="#" data-toggle="modal" data-target="#friendsConfirmedModal" style="text-decoration:none;"><strong><% unless @confirmed.count - 3 <= 0 %> ...e mais <%= @confirmed.count - 3 %><% end %></strong></a>
            </div>
            <div class="mt-1 mb-4">
              <article><%= @event.description %></article>
            </div>
            </div>
            <div class="data-location">
              <div class="d-flex flex-row mr-3 align-items-center mr-4" id="data-location-space">
                <div class="mr-3"><i class="fas fa-calendar-check" style="color:#5c005c; font-size:30px;"></i></div><div style="color:#FF708A;"><strong><%= l @event.date, format: "%a, %d %b %Y at %l:%M %p" %></strong></div>
              </div>
              <div class="d-flex flex-row mr-3 align-items-center" id="selected-suggestion" data-toggle="modal" data-target="#mapModal">
                <% unless @suggestion_selected.nil? %>
                <div class="mr-3"><i class="fas fa-map-marker-alt" style="color:#5c005c; font-size:30px;"></i></div><div style="color:#FF708A;" ><p class="mb-0" style="color: #5C005C;"><strong><%= @suggestion_selected.title %></p><span><%= @suggestion_selected.address %></span></strong></div>

                <% end %>
              </div>
            </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-12 pt-4">
          <div class="menu-add">
            <div id="menu-add-space" data-toggle="tooltip" data-placement="top" title="Suggestions" >
            <i class="fas fa-street-view" style="color:white; font-size:25px; background:#5c005c; padding:10px; border-radius:50px;" data-toggle="modal" data-target="#suggestionModal"></i>
            </div>
            <div data-toggle="tooltip" data-placement="top" title="Invite friends">
            <i class="fas fa-user-plus" style="color:white; font-size:20px; background:#5c005c; padding:12px 10px; border-radius:50px;" data-toggle="modal" data-target="#friendsModal"></i>
            </div>
          </div>
        </div>
      </div>
      <!--End-->

      </div>
    </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 p-0">
        <%= render 'chat' %>
      </div>
  </div>
</div>

<!-- Modal Insertion of Suggestions -->
<div class="modal fade" id="suggestionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Insert a suggestion</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% if @event.user == current_user %>
      <div class="modal-body">
        <%= simple_form_for [@event, @suggestion] do |r| %>
        <%= r.input :title, label: 'Title' %>
        <!-- <input type="search" id="address-input" placeholder="Where are we going?" label="Address"/> -->
        <%= r.input :address, as: :search, label: 'Address', id: 'address-input' %>
        <%= r.button :submit, class:"btn btn-primary" %>
        <% end %>


      </div>
      <% end %>
        <div class="mb-5" style="max-height: 150px; overflow-y: auto; overflow-x: hidden;">
          <% @event.suggestions.each do |suggestion| %>
            <div class="d-flex flex-column mt-2 ml-4 mr-2" style="color:#666666;">
              <% if @event.user == current_user %>
                <div class="d-flex flex-row justify-content-between">
                  <div>
                    <%= link_to suggestion_path(suggestion.id), method: :delete, data: { confirm: "Are you sure you want to delete it?" } do %>
                    <i class="far fa-trash-alt" style="color:#FF708A; margin-right:8px;"></i>
                    <% end %>
                  </div>
                  <div class="flex-grow-1">
                    <span><%= link_to suggestion.title, suggestion_path(suggestion.id), method: :patch %></span>
                  </div>
                  <div>
                    <strong> <span class="mr-2" style="color:#FF708A;">Votes:</span> <%= suggestion.votes.where(status: true).count %></strong>
                  </div>
                </div>
              <% else %>
                <div class="d-flex flex-row justify-content-between align-items-center">

                  <div class="flex-grow-1">
                    <span><%= suggestion.title %></span>
                  </div>
                    <div class="mr-2">
                      <%= link_to suggestion_votes_path(suggestion.id, vote:'down'), method: :post, data: { confirm: "You can only vote once! Are you sure?"} do %>
                        <i class="far fa-thumbs-down" style="color:#5c005c; margin-right:8px; font-size:20px;"></i>
                      <% end %>
                    </div>
                    <div>
                      <%= link_to suggestion_votes_path(suggestion.id, vote:"up"), method: :post, data: { confirm: "You can only vote once! are you sure?"} do %>
                        <i class="far fa-thumbs-up" style="color:#FF708A; margin-right:8px; font-size: 20px;"></i>
                      <% end %>
                    </div>
                </div>
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <%= javascript_pack_tag 'init_autocomplete.js' %>
</div>

<!--Modal for @media for suggestions-->

<!-- Invite a friend modal -->
<div class="modal fade" id="friendsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Invite a friend</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% if @event.user == current_user %>
        <div class="modal-body">
          <%= simple_form_for [@event, @invite] do |f| %>
          <%= f.input :email, label: 'Email'%>
          <%= f.input :message, label: 'Message' %>
          <%= f.submit 'Invite', class:"btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
      <div style="max-height: 150px; overflow-y: auto; overflow-x: hidden;">
        <% @invited.each do |inv| %>
          <div style="border-bottom:1px solid lightgrey;">
            <div class="ml-3"><i class="far fa-user" style="color:#FF708A; margin-right:10px;"></i><%= inv.email %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- Modal Amigos confirmados -->
<div class="modal fade" id="friendsConfirmedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirmed Friends</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <% @event.invites.each do |invite| %>
          <div style="border-bottom:1px solid lightgrey;">
            <div>
            <strong>msg:</strong> <%= invite.message %>
            </div>
            <div>
            <strong>email:</strong>  <%= invite.email %>
            <% if invite.accepted %>
                <i class="fas fa-check" style="color:green;"></i>
              <% else %>
                <i class="fas fa-times" style="color:red;"></i>
              <% end %>
              </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Map Modal -->
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabels" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabels" style="">Local Map</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div
            id="map"
            style="width: 100%; height: 100%;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
      </div>
    </div>
  </div>
</div>